In [34]:
import pandas as pd
import pyarrow

In [35]:
import pandas as pd
df = pd.read_parquet('../data/MEDS/SP_1/shard_events/admissions/[0-160).parquet', engine='pyarrow')
df

,code,subject_id,timestamp
0,IN/TYPE/Indlæggelse,8,1992-01-26 00:00:00
1,IN/TYPE/Indlæggelse,6,2017-02-06 00:00:00
2,IN/TYPE/Indlæggelse,25,2001-06-11 00:00:00
3,IN/TYPE/Tilbage fra orlov,22,2015-10-06 00:00:00
4,IN/TYPE/Flyt_ind,15,2007-01-30 00:00:00
...,...,...,...
155,"OUT/SECTION/NOH COAC0821, ØJENAFD. AMBULATORIE...",15,1982-11-07 00:00:00
156,OUT/SECTION/NEFRO,2,2003-04-03 00:00:00
157,OUT/SECTION/NEFRO,2,2020-03-09 00:00:00
158,OUT/SECTION/CARDIO,20,2017-09-16 00:00:00
159,OUT/SECTION/NEFRO,12,2014-01-25 00:00:00

In [42]:
df = pd.read_parquet('../data/MEDS/SP_1/data/held_out/0.parquet', engine='pyarrow')
df

,subject_id,time,code,numeric_value
0,15,NaT,GENDER//K,NaN
1,15,1971-02-12 00:00:00,DOB,NaN
2,15,1978-06-18 02:01:39,P//PK766,NaN
3,15,1980-01-28 00:56:46,P//PV545,NaN
4,15,1980-03-29 00:00:00,"A//IN/NOH COAC0821, ØJENAFD. AMBULATORIEAFSNIT",NaN
5,15,1981-11-07 03:18:38,LAB//fYtR6cLshS8FvBzGze89,43.696194
6,15,1982-11-07 00:00:00,"A//OUT/NOH COAC0821, ØJENAFD. AMBULATORIEAFSNIT",NaN
7,15,1993-04-22 05:28:25,LAB//KBT,NaN
8,15,1994-12-27 20:12:38,D//DK445,NaN
9,15,2003-05-12 00:55:22,P//PS565,NaN
10,15,2003-08-26 12:11:37,D//DT771,NaN
11,15,2007-01-30 00:00:00,A//IN/CARDIO,NaN
12,15,2010-12-18 23:07:35,D//DP984,NaN
13,15,2015-01-23 23:13:52,D//DN890,NaN
14,15,2016-10-31 07:28:22,P//PR720,NaN
15,15,2018-11-14 06:12:54,D//DS401,NaN
16,15,2020-06-24 00:00:00,A//OUT/CARDIO,NaN
17,15,2020-12-23 20:19:32,D//DB966,NaN
18,20,NaT,GENDER//M,NaN
19,20,1971-04-07 16:01:05,D//DI971,NaN
20,20,1977-07-21 20:14:39,P//PY602,NaN
21,20,1986-04-24 22:14:54,D//DP848,NaN
22,20,1990-05-26 00:00:00,"A//IN/NOH COAC0821, ØJENAFD. AMBULATORIEAFSNIT",NaN
23,20,1990-10-05 00:00:00,A//IN/CARDIO,NaN
24,20,1992-09-24 05:27:58,D//DX949,NaN
25,20,1992-12-12 00:12:32,P//PP320,NaN
26,20,1996-10-30 14:15:49,LAB//wsL4C7DJzfDYswfOdPKmczRLSgDvW2QoE9raw75fs...,NaN
27,20,1997-12-23 22:40:51,D//DZ461,NaN
28,20,1998-03-15 03:02:46,D//DS995,NaN
29,20,2001-10-09 16:04:02,D//DK419,NaN
30,20,2002-02-14 00:00:00,DOB,NaN
31,20,2002-03-13 00:00:00,"A//OUT/NOH COAC0821, ØJENAFD. AMBULATORIEAFSNIT",NaN
32,20,2004-03-18 00:00:00,"A//IN/HGH, AKUTKLINIK GE-GAMMEL",NaN
33,20,2006-09-04 00:00:00,"A//OUT/HGH, AKUTKLINIK GE-GAMMEL",NaN
34,20,2007-02-20 15:36:31,LAB//KBT,57.000000
35,20,2009-12-10 00:00:00,A//OUT/CARDIO,NaN
36,20,2010-07-08 23:51:06,P//PV300,NaN
37,20,2012-03-24 13:24:09,D//DC446,NaN
38,20,2014-12-28 09:59:29,LAB//test;længde,46.413593
39,20,2015-03-17 00:00:00,DOD,NaN
40,20,2016-08-09 00:00:00,A//IN/CARDIO,NaN
41,20,2017-09-16 00:00:00,A//OUT/CARDIO,NaN
42,20,2020-09-17 06:53:51,P//PJ246,NaN
43,24,NaT,GENDER//K,NaN
44,24,1976-03-28 00:00:00,A//IN/CARDIO,NaN
45,24,1977-11-01 01:23:44,D//DU455,NaN
46,24,1981-02-24 18:37:23,D//DB376,NaN
47,24,1982-07-04 00:00:00,A//OUT/CARDIO,NaN
48,24,1983-08-31 17:32:26,LAB//BT,160.000000
49,24,1998-06-09 02:48:16,D//DB592,NaN
50,24,2010-08-07 07:13:11,P//PL172,NaN
51,24,2012-05-02 00:00:00,A//IN/NEFRO,NaN
52,24,2014-01-12 00:00:00,A//OUT/NEFRO,NaN
53,24,2017-07-19 04:38:24,D//DC789,NaN
54,24,2017-10-13 12:26:09,P//PM179,NaN
55,24,2019-03-24 00:00:00,DOB,NaN

In [43]:
df[df['subject_id'] == 15]

,subject_id,time,code,numeric_value
0,15,NaT,GENDER//K,NaN
1,15,1971-02-12 00:00:00,DOB,NaN
2,15,1978-06-18 02:01:39,P//PK766,NaN
3,15,1980-01-28 00:56:46,P//PV545,NaN
4,15,1980-03-29 00:00:00,"A//IN/NOH COAC0821, ØJENAFD. AMBULATORIEAFSNIT",NaN
5,15,1981-11-07 03:18:38,LAB//fYtR6cLshS8FvBzGze89,43.696194
6,15,1982-11-07 00:00:00,"A//OUT/NOH COAC0821, ØJENAFD. AMBULATORIEAFSNIT",NaN
7,15,1993-04-22 05:28:25,LAB//KBT,NaN
8,15,1994-12-27 20:12:38,D//DK445,NaN
9,15,2003-05-12 00:55:22,P//PS565,NaN
10,15,2003-08-26 12:11:37,D//DT771,NaN
11,15,2007-01-30 00:00:00,A//IN/CARDIO,NaN
12,15,2010-12-18 23:07:35,D//DP984,NaN
13,15,2015-01-23 23:13:52,D//DN890,NaN
14,15,2016-10-31 07:28:22,P//PR720,NaN
15,15,2018-11-14 06:12:54,D//DS401,NaN
16,15,2020-06-24 00:00:00,A//OUT/CARDIO,NaN
17,15,2020-12-23 20:19:32,D//DB966,NaN